version: "3"
services:
  myporfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    enviroment:
      - FLASK_ENV=development
    ports:
      "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
volumes:
  mydatabase: